// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ListFiles(arg1:string):Promise<Array<services.FileInfo>>;

export function SelectFolder():Promise<string>;
