// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function ListClones(arg1:string):Promise<services.CloneResult>;

export function ListFiles(arg1:string):Promise<Array<models.FileInfo>>;

export function SelectFolder():Promise<string>;
